services:
  wordpress:
    image: wordpress:latest
    ports:
      - "8080:80"  # Puerto del host: Puerto de WordPress
    environment:
      WORDPRESS_DB_HOST: 10.0.7.25
      WORDPRESS_DB_NAME: CryptoTrackrDB
      WORDPRESS_DB_USER: admin
      WORDPRESS_DB_PASSWORD: admin123
    volumes:
      - cryptotrackr_wordpress:/var/www/html
      - cryptotrackr_domain:/home

volumes:
  cryptotrackr_wordpress:
    external: true
  cryptotrackr_domain:
    external: true
